# Generated by Django 4.0.5 on 2023-04-15 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannydetails',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='nanny_profile_pics'),
        ),
    ]
