# Generated by Django 4.2 on 2023-04-28 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_employerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannydetails',
            name='age_bracket',
            field=models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46 and above', '46 and above'), ('N/A', 'N/A')], default='N/A', max_length=100),
        ),
    ]
