# Generated by Django 4.0.5 on 2023-06-13 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_nannydetails_age_bracket'),
    ]

    operations = [
        migrations.AddField(
            model_name='nannydetails',
            name='good_conduct_certificate',
            field=models.FileField(blank=True, null=True, upload_to='good_conduct/'),
        ),
        migrations.AddField(
            model_name='nannydetails',
            name='id_back_image',
            field=models.ImageField(default='default.png', upload_to='id_images/'),
        ),
        migrations.AddField(
            model_name='nannydetails',
            name='id_front_image',
            field=models.ImageField(default='default.png', upload_to='id_images/'),
        ),
        migrations.AlterField(
            model_name='nannydetails',
            name='image',
            field=models.ImageField(default='default.png', upload_to='nanny_profile_pics'),
        ),
        migrations.AlterField(
            model_name='nannydetails',
            name='language',
            field=models.CharField(choices=[('Kamba', 'Kamba'), ('Kikuyu', 'Kikuyu'), ('Luhya', 'Luhya'), ('Kiswahili', 'Kiswahili'), ('English', 'English')], max_length=200),
        ),
        migrations.AlterField(
            model_name='nannydetails',
            name='level_of_education',
            field=models.CharField(choices=[('College', 'College'), ('High School', 'High School'), ('Primary School', 'Primary School')], max_length=100),
        ),
        migrations.AlterField(
            model_name='nannydetails',
            name='recommendation_letter',
            field=models.FileField(blank=True, null=True, upload_to='recommendations/'),
        ),
    ]
