# Generated by Django 4.0.5 on 2023-06-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_nannydetails_good_conduct_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nannydetails',
            name='id_back_image',
            field=models.ImageField(default=0, upload_to='id_images/'),
        ),
        migrations.AlterField(
            model_name='nannydetails',
            name='id_front_image',
            field=models.ImageField(default=0, upload_to='id_images/'),
        ),
    ]
