# Generated by Django 4.0.5 on 2023-06-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_nannydetails_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nannydetails',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='nanny_profile_pics'),
        ),
    ]
