# Generated by Django 4.0.5 on 2023-06-29 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_employerprofile_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
