# Generated by Django 4.0.5 on 2023-07-12 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_nannydetails_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nannydetails',
            name='language',
            field=models.CharField(max_length=200),
        ),
    ]
