# Generated by Django 4.0.5 on 2023-06-14 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_contractmodel_end_date'),
        ('payment', '0004_employertransactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarypayment',
            name='direct_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.directcontract'),
        ),
        migrations.AlterField(
            model_name='salarypayment',
            name='contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jobapp.contractmodel'),
        ),
    ]
