# Generated by Django 4.2.6 on 2023-10-27 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogcomment_blogcommentreply_delete_blogcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcommentreply',
            name='date_published',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
