# Generated by Django 4.2.6 on 2023-10-27 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blogcommentreply_date_published'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogcommentreply',
            old_name='Blogcomment',
            new_name='blogcomment',
        ),
    ]
