LOCATION_NAMES = (
    ('kileleshwa', 'Kileleshwa'),
    ('dandora', 'Dandora'),
    ('westlands', 'Westlands'),
    ('parklands', 'Parklands'),
    ('langata', 'Lang\'ata'),
    ('karen', 'Karen'),
    ('lavington', 'Lavington'),
    ('kilimani', 'Kilimani'),
    ('runda', 'Runda'),
    ('roysambu', 'Roysambu'),
    ('eastleigh', 'Eastleigh'),
    ('buruburu', 'Buruburu'),
    ('south_c', 'South C'),
    ('south_b', 'South B'),
    ('kasarani', 'Kasarani'),
    ('embakasi', 'Embakasi'),
    ('kawangware', 'Kawangware'),
    ('madaraka', 'Madaraka'),
    ('hurlingham', 'Hurlingham'),
    ('ngong_road', 'Ngong Road'),
    ('airport_west', 'Airport West'),
    ('banana_hill', 'Banana Hill'),
    ('gigiri', 'Gigiri'),
    ('industrial_area', 'Industrial Area'),
    ('juja', 'Juja'),
    ('kibera', 'Kibera'),
    ('limuru', 'Limuru'),
    ('lower_kabete', 'Lower Kabete'),
    ('muthaiga', 'Muthaiga'),
)
