LANGUAGE_CHOICES = (
    ('Kiswahili', 'Kiswahili'),
    ('English', 'English'),
    ('Kamba', 'Kamba'),
    ('Kikuyu', 'Kikuyu'),
    ('Luhya', 'Luhya'),
    ('Luo', 'Luo'),
    ('Kalenjin', 'Kalenjin'),
    ('Meru', 'Meru'),
    ('Embu', 'Embu'),
    ('Maasai', 'Maasai'),
    ('Kisii', 'Kisii'),
    ('Turkana', 'Turkana'),
    ('Mijikenda', 'Mijikenda'),
    ('Somali', 'Somali'),
    ('Swahili', 'Swahili'),
    ('Rendille', 'Rendille'),
    ('Samburu', 'Samburu'),
    ('Orma', 'Orma'),
    ('Taita', 'Taita'),
    ('Giriama', 'Giriama'),
    ('Pokomo', 'Pokomo'),
    ('Dahalo', 'Dahalo'),
    ('Gusii', 'Gusii'),
    ('Ribe', 'Ribe'),
    ('Tharaka', 'Tharaka'),
    ('Bajuni', 'Bajuni'),
    ('Tesoo', 'Tesoo'),
    ('Kupsabiny', 'Kupsabiny'),
    ('Chonyi', 'Chonyi'),
    ('Wanga', 'Wanga'),
    ('Kuria', 'Kuria'),
    ('Kikamba', 'Kikamba'),
    ('Ogiek', 'Ogiek'),
    ('El Molo', 'El Molo'),
    ('Nandi', 'Nandi'),
    ('Segeju', 'Segeju'),
    # Add more languages as needed
)
