# Generated by Django 4.0.5 on 2023-04-17 11:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Full-time Nanny', 'full-time nanny'), ('Part-time Nanny', 'parttime nanny'), ('Live-in Nanny', 'live-in nanny'), ('Live-out Nanny', 'Live-out Nanny'), ('Night Nanny', 'night nanny')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('addresss', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('nanny_age', models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46 and above', '46 and above'), ('No preference', 'No preference')], max_length=100)),
                ('hours_per_day', models.IntegerField(default=2)),
                ('start_date', models.DateField()),
                ('years_of_experience', models.IntegerField(default=0)),
                ('duration', models.CharField(choices=[('Less than 6 months', 'less than 6 months'), ('1 - 2 Years', '1 - 2 years'), ('3 -6 years', '3 - 6 years'), ('More than 7 years', 'more than 7 years')], max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField(blank=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ContractModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField()),
                ('duration', models.CharField(choices=[('Less than 6 months', 'less than 6 months'), ('1 - 2 Years', '1 - 2 years'), ('3 -6 years', '3 - 6 years'), ('More than 7 years', 'more than 7 years')], max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=100)),
                ('company_commission', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('employer', models.ForeignKey(limit_choices_to={'groups__name': 'employer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobmodel')),
                ('nanny', models.ForeignKey(limit_choices_to={'user__groups__name': 'nanny'}, on_delete=django.db.models.deletion.CASCADE, to='users.nannydetails')),
            ],
        ),
    ]
