# Generated by Django 4.1.1 on 2023-04-14 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='jobModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Full-time Nanny', 'full-time nanny'), ('Part-time Nanny', 'parttime nanny'), ('Live-in Nanny', 'live-in nanny'), ('Live-out Nanny', 'Live-out Nanny'), ('Night Nanny', 'night nanny')], max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('addresss', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=100)),
                ('language', models.CharField(choices=[('Swahili', 'Swahili'), ('English', 'English'), ('Kikuyu', 'Kikuyu'), ('Luhya', 'Luhya'), ('Kalenjin', 'Kalenjin'), ('Luo', 'Luo'), ('Kamba', 'Kamba'), ('Meru', 'Meru'), ('Gusii', 'Gusii'), ('Somali', 'Somali')], max_length=100)),
                ('nanny_age', models.CharField(max_length=100)),
                ('hours_per_day', models.IntegerField(default=2)),
                ('start_data', models.DateField()),
                ('years_of_experience', models.IntegerField(default=0)),
                ('duration', models.CharField(choices=[('Less than 6 months', 'less than 6 months'), ('1 - 2 Years', '1 - 2 years'), ('3 -6 years', '3 - 6 years'), ('More than 7 years', 'more than 7 years')], max_length=100)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('job_description', models.TextField(blank=True)),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
