# Generated by Django 4.1.1 on 2023-04-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='nanny_age',
            field=models.CharField(choices=[('18-25', '18-25'), ('26-35', '26-35'), ('36-45', '36-45'), ('46 and above', '46 and above'), ('No preference', 'No preference')], max_length=100),
        ),
    ]
