# Generated by Django 4.0.5 on 2023-04-18 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_remove_contractmodel_company_commission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contractmodel',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='job',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='nanny',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='contractmodel',
            name='status',
        ),
    ]
