# Generated by Django 4.1.1 on 2023-04-14 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_alter_jobmodel_nanny_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmodel',
            old_name='start_data',
            new_name='start_date',
        ),
    ]
