# Generated by Django 4.2 on 2023-04-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0003_rename_start_data_jobmodel_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='language',
            field=models.CharField(choices=[('Swahili', 'swahili'), ('English', 'english'), ('Kikuyu', 'kikuyu'), ('Luhya', 'luhya'), ('Kalenjin', 'kalenjin'), ('Luo', 'luo'), ('Kamba', 'kamba'), ('Meru', 'meru'), ('Gusii', 'gusii'), ('Somali', 'somali')], max_length=100),
        ),
    ]
