# Generated by Django 4.2 on 2023-04-20 05:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_employerprofile'),
        ('jobapp', '0003_remove_contractmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='company_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='duration',
            field=models.CharField(choices=[('Less than 6 months', 'less than 6 months'), ('1 - 2 Years', '1 - 2 years'), ('3 -6 years', '3 - 6 years'), ('More than 7 years', 'more than 7 years')], default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='employer',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'employer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 20, 5, 30, 49, 961762, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='job',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='jobapp.jobmodel'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='nanny',
            field=models.ForeignKey(default=1, limit_choices_to={'user__groups__name': 'nanny'}, on_delete=django.db.models.deletion.CASCADE, to='users.nannydetails'),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='contractmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated')], default='pending', max_length=100),
        ),
    ]
