# Generated by Django 4.2 on 2023-04-14 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_alter_jobmodel_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmodel',
            name='language',
            field=models.CharField(max_length=100),
        ),
    ]
