# Generated by Django 4.2 on 2023-04-24 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0004_contractmodel_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 24, 5, 40, 46, 479267, tzinfo=datetime.timezone.utc)),
        ),
    ]
