# Generated by Django 4.0.5 on 2023-04-26 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0006_alter_contractmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 26, 13, 57, 23, 398569, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('canceled', 'Canceled'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
