# Generated by Django 4.2 on 2023-04-29 07:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0008_alter_contractmodel_end_date_directcontract'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontract',
            name='job_category',
            field=models.CharField(choices=[('Full-time Nanny', 'full-time nanny'), ('Part-time Nanny', 'parttime nanny'), ('Live-in Nanny', 'live-in nanny'), ('Live-out Nanny', 'live-out nanny'), ('Night Nanny', 'night nanny')], default='Full-time Nanny', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 5, 29, 7, 28, 28, 335206, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='category',
            field=models.CharField(choices=[('Full-time Nanny', 'full-time nanny'), ('Part-time Nanny', 'parttime nanny'), ('Live-in Nanny', 'live-in nanny'), ('Live-out Nanny', 'live-out nanny'), ('Night Nanny', 'night nanny')], max_length=100),
        ),
    ]
