# Generated by Django 4.0.5 on 2023-05-12 15:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0010_alter_contractmodel_end_date_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 11, 15, 54, 35, 578982, tzinfo=utc)),
        ),
    ]
