# Generated by Django 4.0.5 on 2023-05-13 07:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0012_rating_receiver_alter_contractmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 12, 7, 41, 45, 967335, tzinfo=utc)),
        ),
    ]
