# Generated by Django 4.0.5 on 2023-06-15 13:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0018_alter_contractmodel_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmodel',
            name='days_off',
            field=models.CharField(choices=[('Every weekend', 'Every weekend'), ('Every Saturday', 'Every Saturday'), ('Every Sunday', 'Every Sunday'), ('Second Saturday every month', 'Second Saturday every month'), ('Second Sunday every month', 'Second Sunday every month'), ('Last Saturday every month', 'Last Saturday every month'), ('Last Sunday every month', 'Last Sunday every month'), ('Others', 'Others')], default='Every weekend', max_length=100),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='leave_available',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AddField(
            model_name='jobmodel',
            name='vacation_days_per_year',
            field=models.CharField(choices=[('One month', 'One month'), ('Two weeks', 'Two weeks'), ('One week', 'One week'), ('Others', 'Others')], default='Two weeks', max_length=100),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 13, 13, 35, 736987, tzinfo=utc)),
        ),
    ]
