# Generated by Django 4.0.5 on 2023-06-15 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0019_jobmodel_days_off_jobmodel_leave_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 15, 13, 48, 3, 147388, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='vacation_days_per_year',
            field=models.CharField(choices=[('1 month', '1 month'), ('3 weeks', '3 weeks'), ('2 weeks', '2 weeks'), ('1 week', '1 week'), ('Others', 'Others')], default='Two weeks', max_length=100),
        ),
    ]
