# Generated by Django 4.0.5 on 2023-06-20 13:08

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0008_alter_nannydetails_image'),
        ('jobapp', '0020_alter_contractmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractmodel',
            name='nanny_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='nanny_signatures/'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 20, 13, 8, 1, 70680, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='SignedContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='signatures/')),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.contractmodel')),
                ('nanny', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.nannydetails')),
            ],
        ),
        migrations.CreateModel(
            name='EmployerSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature_image', models.ImageField(upload_to='employer_signatures/')),
                ('date_signed', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobapp.contractmodel')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
