# Generated by Django 4.0.5 on 2023-06-22 13:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0021_contractmodel_nanny_signature_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 22, 13, 0, 48, 739690, tzinfo=utc)),
        ),
    ]
