# Generated by Django 4.0.5 on 2023-06-30 12:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0023_alter_contractmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 12, 13, 44, 163809, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='jobmodel',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
