# Generated by Django 4.0.5 on 2023-06-30 12:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0024_alter_contractmodel_end_date_alter_jobmodel_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 7, 30, 12, 34, 28, 998603, tzinfo=utc)),
        ),
    ]
