# Generated by Django 4.0.5 on 2023-07-10 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0030_alter_contractmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directcontract',
            name='nanny_signature_image',
            field=models.ImageField(blank=True, null=True, upload_to='nanny_signatures/'),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 9, 10, 12, 58, 327610, tzinfo=utc)),
        ),
    ]
