# Generated by Django 4.0.5 on 2023-07-14 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0032_alter_contractmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 13, 16, 1, 6, 698817, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='contractmodel',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('accepted', 'Accepted')], default='pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='directcontract',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('terminated', 'Terminated'), ('accepted', 'Accepted')], default='pending', max_length=100),
        ),
    ]
