# Generated by Django 4.2.3 on 2023-07-28 15:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0033_alter_contractmodel_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 8, 27, 15, 53, 30, 319512, tzinfo=datetime.timezone.utc)),
        ),
    ]
