# Generated by Django 4.2.6 on 2023-10-25 11:36

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobapp', '0035_alter_contractmodel_end_date_savedjobmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 24, 11, 35, 56, 879754, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterUniqueTogether(
            name='savedjobmodel',
            unique_together={('user', 'job')},
        ),
    ]
