# Generated by Django 4.2.6 on 2023-10-28 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0042_alter_contractmodel_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractmodel',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 11, 27, 3, 37, 31, 537480, tzinfo=datetime.timezone.utc)),
        ),
    ]
